# This just exists for runtest.py
application: fluent-testapp
version: 1
runtime: python27
threadsafe: yes

libraries:
- name: webob
  version: 1.2.3

- name: webapp2
  version: 2.5.2

# pretend we're a proper app
handlers:
- url: /
  static_dir: .
